### ISSUE TITLE
[Doubt]

### ISSUE THREAD

**Issue by r1goo** [timsly/carrierwave-serializable#21]
Hi everyone! Just me asking about an error.
I already properly install Carrierwave with multiple uploads, and now just trying to add serializable functionality for all those images.

My question is how should i define the hash in the whitelist parameters to accept a Hash variable.

Im getting the error: Attribute was supposed to be a Hash, but was a Array. -- []

The only place an array may appear (i think) its here:

def used_car_params
      params.require(:used_car).permit(........,  {pictures: []},
    ...
end

At least that works with simple multi uploads.

PD: Already did everything as explain before to configure, but looks like i miss something.
Thanks in advance.

**Comment by timsly** [comment]
Hi @r1goo 
This is `strong_parameters` issue.
If you want to permit hash, you need to do following
```ruby
params.require(:used_car).permit(pictures: [:file1, :file2])
```
or for dynamic hash keys
```ruby
params.require(:used_car).tap do |whitelisted|
  whitelisted[:pictures] = params[:used_car][:used_car]
end
```

**Comment by r1goo** [comment]
Hi! Thanks for your reply.
The user is able to  select several files and at first there's no restriction about that. I that case should I implement something with dynamic hash? Because I understand that with :file1, :file2 and if the user upload for example 3 files that will crashed. Am I right? Maybe it's a n00b question but I'm in my second ruby month. Thanks in advance

**Comment by timsly** [comment]
Yes, you should better go with dynamic one

**Comment by r1goo** [comment]
Thanks for the guiadance.
Now im trying something

**Comment by r1goo** [comment]
Thanks for your help, but did you meant something like this instead?

params.require(:used_car).tap do |whitelisted|
  whitelisted[:pictures] = params[:used_car][:pictures]
end
Seems to be good enough for me, but unfortunately im still getting the same error :(

Something like this its what i have at the moment:

def used_car_params
      params.require(:used_car).permit(:marca, :modelo, ..., :transmisions,
      used_sell_attributes: [:precio,
                             :notas],
      used_sound_attributes: [:id,
                              :radio, 
                              :bluetooth],
      used_confort_attributes: [:id,
                                :aireAcondicionado,
                                ....
    ],
    used_security_attributes: [:id,
                                :alarma,
                               ...
                                :controlEstabilidad]
    
    ).tap do |whitelisted|
        whitelisted[:pictures] = params[:used_car][:pictures]
      end
    end

Thank you all!

**Comment by timsly** [comment]
Yes, it was only example. You need to use you own code there, but just add `.tap do |whitelisted|` in the end

**Comment by r1goo** [comment]
Thanks for the reply Tim!
That was exactly wat i did, but nothing happen.
At this time thats what i have done:

 params.require(:used_car).permit(:marca, :modelo, ...
      used_sell_attributes: [:precio,
                             :notas],
      ).tap do |whitelisted|
        whitelisted[:pictures] = params[:used_car][:pictures]
        end

In my HTML: 
<div class="field">
    <%= f.label :pictures %><br>
    <%= f.file_field :pictures, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png" %>
  </div>

My schema.db:

create_table "used_cars", force: :cascade do |t|
    t.string   "marca"
    t.string   "modelo"
     ....
    t.datetime "created_at",               null: false
    t.datetime "updated_at",               null: false
    t.string   "transmision"
    t.text     "images",      default: [],              array: true
    t.text     "pictures"
  end

also tryed with  "t.text     "images",      default: [],   array: true" but nothing happen

My Model:

class UsedCar < ApplicationRecord
    serialize :pictures, Hash
    mount_uploaders :images, ImageUploader, serialize_to: :pictures
end

I also follow step by step the tutorial to properly install but nothing happen. 
Please can you tell me if im forgeting something?

I have no idea where to go and i been reading all the internet and explains the same, but i do not understand what im doing wrong. Its very important to me get solved this problem.

Thanks again and sorry to bother you again

**Comment by timsly** [comment]
This gem is not designed to work with dynamic hash at all, you need to explicitly pass `:image1`, `:image2` and it will store it to the serialized hash.
You cannot handle unlimited files with it, so that's why code above didn't work.

**Comment by timsly** [comment]
In general, instead of writing carrierwave data to some field, it will write it to hash with given key(`document1` from README) and then serialize it to some field(`documents` from README)

**Comment by r1goo** [comment]
Thanks bro! im gonna try with all these changes!
